apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: fcg-users
type: kubernetes.io/dockerconfigjson
data:
  # Replace with your ACR credentials in base64
  # To generate, run:
  # kubectl create secret docker-registry acr-secret \
  #   --docker-server=fiapcr.azurecr.io \
  #   --docker-username=<ACR_USERNAME> \
  #   --docker-password=<ACR_PASSWORD> \
  #   --docker-email=<YOUR_EMAIL> \
  #   --namespace=fcg-users \
  #   --dry-run=client -o yaml
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>
