apiVersion: v1
kind: ServiceAccount
metadata:
  name: fcg-users-sa
  namespace: fcg-users
  labels:
    app: fcg-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fcg-users-role
  namespace: fcg-users
  labels:
    app: fcg-users
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fcg-users-rolebinding
  namespace: fcg-users
  labels:
    app: fcg-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fcg-users-role
subjects:
  - kind: ServiceAccount
    name: fcg-users-sa
    namespace: fcg-users
