apiVersion: v1
kind: Secret
metadata:
  name: fcg-users-secret
  namespace: fcg-users
type: Opaque
data:
  JwtSettings__SecretKey: ejNGKzdzcjh2TjVZbEcxYVhiMmo4S3FIMHlMOXVEM3ZNNHBRNXJUNnNVOD0=
  
  # Connection String (base64 encoded)
  ConnectionStrings__DefaultConnection: U2VydmVyPXRjcDpmY2ctdXNlci1zcWxzZXJ2ZXIuZGF0YWJhc2Uud2luZG93cy5uZXQsMTQzMztJbml0aWFsIENhdGFsb2c9ZmNnX3VzZXI7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO1VzZXIgSUQ9c3FsYWRtaW47UGFzc3dvcmQ9WW91clBhc3N3b3JkMTIzKio7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=
